### PR TITLE
Fixed PyPI name in setup

### PR DESCRIPTION
**Pull request by makermelissa**
Oopsy :)

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
Do you think the PyPortal portion will be confusing? Maybe just Portal? That way it doesn't match a hardware name.

**Comment by makermelissa** [comment]
Well, the purpose is to emulate the PyPortal over Blinka, so I think Portal would be even more confusing. :)

**Comment by tannewt** [comment]
My worry is that it won't run on PyPortal and people will try to. In general, we should be careful reusing names across to Blinka and Arduino because it can be confusing.

**Review by ladyada — APPROVED** [review]

**Comment by makermelissa** [comment]
I'll open an issue to make it more clear that this only runs on CPython.

**Comment by FoamyGuy** [comment]
Perhaps in the longer term there is room for a conversation about renaming the PyPortal library?

It's named after the PyPortal and is made to work well on that device. But the actual functionality within the library is a bit more generic. It's kind of like an "easy button" wrapper around `adafruit_requests` and `adafruit_esp32spi` and some of the displayio modules to allow for minimal code to get basic IoT style dashboards and displays  populated with data from the internet. 

As time goes on and internet access and screens becomes more widespread amongst the microcontroller options this library can provide nice functionality on devices that are not specifically PyPortal's

**Pull request merged**
